name: 5-Min Free Live
on:
  workflow_dispatch:
    inputs:
      stream_key:
        description: 'YouTube Stream Key'
        required: true
      video_url:
        description: 'Video URL'
        required: true

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Streaming
        run: |
          # ঠিক ৩০০ সেকেন্ড পর অটোমেটিক কিল হবে
          timeout 300s ffmpeg -re -i "${{ github.event.inputs.video_url }}" \
          -vcodec libx264 -preset veryfast -b:v 2500k -acodec aac -f flv \
          "rtmp://a.rtmp.youtube.com/live2/${{ github.event.inputs.stream_key }}" || true
